stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/train.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train_clean.csv
      - params.yaml
    metrics:
      - metrics.json:
          cache: false

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
      - data/processed/train_clean.csv
